services:
  frontend:
    container_name: charactyr-frontend
    image: charactyr/frontend
    ports:
      - "443:8080"
    secrets:
      - charactyr_frontend_cert_key

  keycloak:
    container_name: charactyr-auth-keycloak
    image: bitnami/keycloak
    ports:
      - "8443:8443"
    depends_on:
      - auth-db
    environment:
      KEYCLOAK_ENABLE_HTTPS: true
      KEYCLOAK_HTTPS_USE_PEM: true
      KEYCLOAK_HTTPS_CERTIFICATE_FILE: /opt/bitnami/keycloak/certs/charactyr-auth-keycloak.pem
      KEYCLOAK_HTTPS_CERTIFICATE_KEY_FILE: /run/secrets/charactyr_auth_keycloak_cert_key
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_HOST: charactyr-auth-postgres
      KEYCLOAK_DATABASE_PORT: 5433
      KEYCLOAK_DATABASE_USER: postgres
      KEYCLOAK_DATABASE_PASSWORD: password
      KEYCLOAK_DATABASE_NAME: charactyr-user-management
      KEYCLOAK_EXTRA_ARGS: "--import-realm"
    volumes:
      - ./deployment/certs/charactyr-auth-keycloak.pem:/opt/bitnami/keycloak/certs/charactyr-auth-keycloak.pem
      - ./deployment/keycloak-config.json:/opt/bitnami/keycloak/data/import/keycloak-config.json
      - ./frontend/charactyr-theme:/opt/bitnami/keycloak/themes/charactyr-theme
    secrets:
      - charactyr_auth_keycloak_cert_key

  backend-db:
    container_name: charactyr-backend-postgres
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: charactyr-app-management
    volumes:
      - ./deployment/charactyr-app-management:/var/lib/postgresql/data

  auth-db:
    container_name: charactyr-auth-postgres
    image: postgres
    restart: always
    ports:
      - "5433:5433"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: charactyr-user-management
      PGPORT: 5433
    volumes:
      - ./deployment/charactyr-user-management:/var/lib/postgresql/data

secrets:
  charactyr_frontend_cert_key:
    file: ./deployment/certs/charactyr-frontend.key
  charactyr_auth_keycloak_cert_key:
    file: ./deployment/certs/charactyr-auth-keycloak-key.pem