@startuml
actor User as User

rectangle "Character Builder" {
  [<<Container>>\nFrontend • nginx] as Frontend

  rectangle "Anwendungsverwaltung" {
  [<<Container>>\nREST API • Java Spring Boot] as SpringBootBackend
    Database "<<Container>>\n Datenbank • PostgreSQL" as NonUserDataDb
  }

  rectangle "Nutzerverwaltung" {
      Database "<<Container>>\n Datenbank • PostgreSQL" as UserDataDb
      [<<Container>>\nAuthentifizierungsserver • Keycloak IAM] as AuthServer
  }

  User <----> Frontend
  User <--> AuthServer

  User <-> SpringBootBackend
  SpringBootBackend <. NonUserDataDb
  AuthServer <. UserDataDb
}
@enduml